# Generated by Django 6.1.1 on 2026-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_text', models.TextField(blank=True)),
                ('argv', models.JSONField(blank=True, default=list)),
                ('security_decision', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('denied', 'Denied'), ('confirm_required', 'Confirm required'), ('skipped', 'Skipped')], max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='flows.action')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
