# Generated by Django 6.1.1 on 2026-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('application', 'Application'), ('game', 'Game'), ('movie', 'Movie'), ('tv_show', 'TV show'), ('music', 'Music'), ('website', 'Website'), ('person', 'Person'), ('device', 'Device'), ('service', 'Service'), ('file', 'File'), ('folder', 'Folder')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.5)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'indexes': [models.Index(fields=['normalized_name', 'type'], name='knowledge_e_normali_85f501_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('confidence', models.FloatField(default=0.5)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='knowledge.entity')),
            ],
            options={
                'verbose_name_plural': 'aliases',
                'constraints': [models.UniqueConstraint(fields=('entity', 'normalized_alias'), name='uniq_alias_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='IntentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('normalized_phrase', models.CharField(db_index=True, max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='knowledge.intent')),
            ],
            options={
                'verbose_name_plural': 'intent aliases',
                'constraints': [models.UniqueConstraint(fields=('normalized_phrase',), name='uniq_intent_alias_phrase')],
            },
        ),
    ]
