# Generated by Django 6.1.1 on 2026-09-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intent',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intent',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intent',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intentalias',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='plugin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='AliasCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_phrase', models.CharField(max_length=255)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_candidates', to='knowledge.entity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('normalized_phrase', 'entity'), name='uniq_alias_candidate')],
            },
        ),
    ]
