# Generated by Django 6.1.1 on 2026-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='cache_layer',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='estimated_tokens_without_econ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='match_method',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='tokens_saved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
