# Generated by Django 6.1.1 on 2026-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('executor', models.CharField(default='shell', max_length=64)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('security_level', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confidence', models.FloatField(default=0.5)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='knowledge.intent')),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=64)),
                ('node_type', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_nodes', to='flows.action')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_nodes', to='knowledge.entity')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flows.flow')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flows.flow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='flows.flownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='flows.flownode')),
            ],
        ),
        migrations.CreateModel(
            name='ActionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flows.action')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('action', 'version'), name='uniq_action_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_flow_version'),
        ),
        migrations.AddConstraint(
            model_name='flownode',
            constraint=models.UniqueConstraint(fields=('flow', 'node_key'), name='uniq_flow_node_key'),
        ),
    ]
