# Generated by Django 6.1.1 on 2026-09-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
        ('knowledge', '0002_alias_last_used_at_entity_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flownode',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_nodes', to='knowledge.provider'),
        ),
    ]
