# Generated by Django 6.1.1 on 2026-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('requests_total', models.PositiveIntegerField(default=0)),
                ('llm_calls_total', models.PositiveIntegerField(default=0)),
                ('cache_hits_total', models.PositiveIntegerField(default=0)),
                ('execution_success_total', models.PositiveIntegerField(default=0)),
                ('execution_failure_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
