# Generated by Django 6.1.1 on 2026-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='avg_latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='tokens_consumed_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='tokens_saved_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
