# Generated by Django 6.1.1 on 2026-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=128)),
                ('prompt', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='requests.requestlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
