/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HermesRouteImport } from './routes/hermes'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as OptimizationsRouteImport } from './routes/optimizations'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as FlowsFlowIdRouteImport } from './routes/flows.$flowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesRoute = HermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationsRoute = OptimizationsRouteImport.update({
  id: '/optimizations',
  path: '/optimizations',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => FlowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flows': typeof FlowsRouteWithChildren
  '/graph': typeof GraphRoute
  '/hermes': typeof HermesRoute
  '/knowledge': typeof KnowledgeRoute
  '/optimizations': typeof OptimizationsRoute
  '/requests': typeof RequestsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flows': typeof FlowsRouteWithChildren
  '/graph': typeof GraphRoute
  '/hermes': typeof HermesRoute
  '/knowledge': typeof KnowledgeRoute
  '/optimizations': typeof OptimizationsRoute
  '/requests': typeof RequestsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flows': typeof FlowsRouteWithChildren
  '/graph': typeof GraphRoute
  '/hermes': typeof HermesRoute
  '/knowledge': typeof KnowledgeRoute
  '/optimizations': typeof OptimizationsRoute
  '/requests': typeof RequestsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows'
    | '/graph'
    | '/hermes'
    | '/knowledge'
    | '/optimizations'
    | '/requests'
    | '/flows/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flows'
    | '/graph'
    | '/hermes'
    | '/knowledge'
    | '/optimizations'
    | '/requests'
    | '/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/flows'
    | '/graph'
    | '/hermes'
    | '/knowledge'
    | '/optimizations'
    | '/requests'
    | '/flows/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsRoute: typeof FlowsRouteWithChildren
  GraphRoute: typeof GraphRoute
  HermesRoute: typeof HermesRoute
  KnowledgeRoute: typeof KnowledgeRoute
  OptimizationsRoute: typeof OptimizationsRoute
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes': {
      id: '/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof HermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizations': {
      id: '/optimizations'
      path: '/optimizations'
      fullPath: '/optimizations'
      preLoaderRoute: typeof OptimizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof FlowsRoute
    }
  }
}

interface FlowsRouteChildren {
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
}

const FlowsRouteChildren: FlowsRouteChildren = {
  FlowsFlowIdRoute: FlowsFlowIdRoute,
}

const FlowsRouteWithChildren = FlowsRoute._addFileChildren(FlowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsRoute: FlowsRouteWithChildren,
  GraphRoute: GraphRoute,
  HermesRoute: HermesRoute,
  KnowledgeRoute: KnowledgeRoute,
  OptimizationsRoute: OptimizationsRoute,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
