# Generated by Django 6.1.1 on 2026-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plugin',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plugin',
            name='discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='entity_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plugin',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plugin',
            name='source_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.CharField(default='0.1.0', max_length=32),
        ),
    ]
